TfWM Updates
wmcadigital/wmn-disruption-email-templates pull request #41
Opened 2021-06-14 11:18 UTC by houbly

- Updated links to tfwm.org.uk
- Updated to tfwm logo text
- Added hidden preheader text to show better email preview descriptions

2021-06-14 12:22 UTC, mrmjprice requested changes
Couple of changes here to help screen readers and also update a link. Thanks.

2021-06-14 12:22 UTC, mrmjprice commented on src/partials/header.mjml
> +      alt="Transport for West Midlands logo"
Leave alt text blank for this as screen readers won't have a great experience hearing the same thing twice

2021-06-14 12:22 UTC, mrmjprice commented on src/partials/header.mjml
>        href="https://www.wmca.org.uk"
Should link to https://www.tfwm.org.uk

2021-06-14 12:22 UTC, mrmjprice commented on src/partials/header.mjml
> +      alt="Transport for West Midlands logo text"
Change to "Transport for West Midlands"

2021-07-08 09:47 UTC, catiarodriguescosta approved these changes
👍

2021-07-08 09:51 UTC, daylesalmon approved these changes

2021-07-08 10:03 UTC, merged